### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by travi** [gr2m/merge-dependency-update-prs#1]
not sure this belongs directly in this tool, but its something i've kind of wanted with my use of greenkeeper-keeper for some time, so i figure its worth at least sharing. feel free to close as out-of-scope if you dont think it fits here.

even for successfully merged greenkeeper PRs, i try to read through the release notes of the packages that were updated. however, the same package is often updated across several packages. i don't need to read it each time, but keeping straight which ive read among the PRs for various packages is sometimes a chore. 

so, i've considered putting together a way to pull the release notes from the PRs, dedupe, and clear/mark-done (if using the beta version of notifications) all of the notifications for that particular update.

**Comment by gr2m** [comment]
> my use of greenkeeper-keeper

Oh I forgot to mention greenkeeper-keeper in the readme! I'm sure folks will be interested in it. I'm just to afraid to enable fully automated merging for myself

> even for successfully merged greenkeeper PRs, i try to read through the release notes of the packages that were updated

Me too! Always!

> so, i've considered putting together a way to pull the release notes from the PRs, dedupe, and clear/mark-done (if using the beta version of notifications) all of the notifications for that particular update.

That sounds very cool! 

I wonder if `greenkeeper-keeper` could add that as a feature, together with holding off merging, but actually letting me review the PRs grouped by the dependency that was updated, with its changelogs. 

It really is something that I wish Greenkeeper would do itself, but I'm not holding my breath :(

**Comment by travi** [comment]
> I wonder if greenkeeper-keeper could add that as a feature

i've certainly considered it. mostly has been an issue of finding time to implement. i've partly been hesitant since greenkeeper-keeper is currently fully headless and this seems like it would need a ui or at least a cli. 

i've also been hesitant to continue investment in the current version vs getting migrated to probot. i still hope there is room for sharing the logic and keeping both around, but not sure there.

> together with holding off merging

i don't intend to add logic that would prevent merging directly into greenkeeper-keeper. however, since it will only merge if all checks are passing, it could certainly be added as another check. maybe that point highlights that this feature is at least separate from greenkeeper-keeper, but could be used as a complimentary tool. 

while i personally wouldnt want to delay the merge until reviewing the release notes because of the extra manual steps that come up when a follow up version gets published before merging the first, it could at least work so that approval in the separate tool would make the check pass in impacted PRs and greenkeeper-keeper then acts on all of them.

**Comment by gr2m** [comment]
That all makes sense.

This is all out of scope for this little CLI though, so I'll go ahead and close the issue
